#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# ВАЖНО (см. docs/build-status.md): этот скрипт — стандартный Gradle wrapper
# launcher. Для его работы рядом должен лежать gradle/wrapper/gradle-wrapper.jar.
# В этом ZIP-архиве .jar-файл ОТСУТСТВУЕТ (бинарный файл, скачивается автоматически
# при первом Gradle Sync в Android Studio или командой `gradle wrapper` при наличии
# интернета) — офлайн-песочница, в которой готовился проект, не имеет доступа в сеть.
##############################################################################

APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    die "ERROR: $CLASSPATH не найден.

Это ожидаемо для этого офлайн-сгенерированного архива — см. docs/build-status.md.
Откройте проект в Android Studio (Gradle Sync докачает wrapper автоматически) или
выполните 'gradle wrapper --gradle-version 8.7', если у вас установлен Gradle локально."
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$(basename "$0")" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
